AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  GetRessources:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: routes.getRessources
      CodeUri: ./src
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /ressource
            Method: GET
  RoutineDay:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: routes.day
      Timeout: 60
      CodeUri: ./src
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /day
            Method: GET
  Consume:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "consume"
      Runtime: nodejs8.10
      Handler: lambdas/ressources.consume
      CodeUri: ./src
  Refill:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "refill"
      Runtime: nodejs8.10
      Handler: lambdas/ressources.refill
      CodeUri: ./src
  Kill:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "kill"
      Runtime: nodejs8.10
      Handler: lambdas/ressources.kill
      CodeUri: ./src
  Supply:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "supply"
      Timeout: 60
      Runtime: nodejs8.10
      Handler: lambdas/supply.supply
      CodeUri: ./src