AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time

Globals:
  Function:
    Runtime: nodejs8.10
    Environment:
      Variables:
        REGION: "eu-west-3"

Resources:
  RoutineDay:
    Type: AWS::Serverless::Function
    Properties:
      Handler: routine-service/index.day
      CodeUri: ./src
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /day
            Method: GET

  GetRessources:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ressources-service/index.getRessources
      CodeUri: ./src
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /ressource
            Method: GET

  Consume:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "consume"
      Handler: ressources-service/index.consume
      CodeUri: ./src
  Refill:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "refill"
      Handler: ressources-service/index.refill
      CodeUri: ./src

  Kill:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "kill"
      Handler: ressources-service/index.kill
      CodeUri: ./src

  Supply:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "supply"
      Handler: ressources-service/index.supply
      CodeUri: ./src

  Work:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "work"
      Handler: ressources-service/index.work
      CodeUri: ./src