AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  GetRessources:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: routes.getRessources
      CodeUri: ./src
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /ressource
            Method: GET
  Consume:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "consume"
      Runtime: nodejs8.10
      Handler: lambdas/ressources.consume
      CodeUri: ./src
  Refill:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: routes.refill
      CodeUri: ./src
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /refill/{ressourceType}
            Method: PUT
  KillHuman:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: routes.kill
      CodeUri: ./src
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /kill/{beingType}
            Method: PUT
  KillRobot:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: routes.kill
      CodeUri: ./src
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /kill/{beingType}
            Method: PUT
  Supply:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: routes.supply
      CodeUri: ./src
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /supply/{beingType}
            Method: PUT