AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: index.handler
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /ressource
            Method: GET